include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_null_aware_elements: false
    # 성능 최적화 린트 규칙
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_build_context_synchronously: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_redundant_argument_values: true

analyzer:
  errors:
    prefer_const_constructors: info
    prefer_const_constructors_in_immutables: info
    prefer_const_declarations: info
    prefer_const_literals_to_create_immutables: info
