import 'package:guda_chatbot/features/chat/domain/entities/hexagram.dart';

const List<Hexagram> hexagramData = [
  Hexagram(
    id: 1,
    name: '중천건',
    hanja: '重天乾',
    binary: '111111',
    summary: '하늘의 기운이 충만함',
  ),
  Hexagram(
    id: 2,
    name: '중지곤',
    hanja: '重地坤',
    binary: '000000',
    summary: '대지의 유순함',
  ),
  Hexagram(
    id: 3,
    name: '수뢰둔',
    hanja: '水雷屯',
    binary: '100010',
    summary: '어려움 속의 발아',
  ),
  Hexagram(
    id: 4,
    name: '산수몽',
    hanja: '山水蒙',
    binary: '010001',
    summary: '어린 아이의 어리석음',
  ),
  Hexagram(
    id: 5,
    name: '수천수',
    hanja: '水天需',
    binary: '111010',
    summary: '때를 기다림',
  ),
  Hexagram(
    id: 6,
    name: '천수송',
    hanja: '天水訟',
    binary: '010111',
    summary: '송사 및 다툼',
  ),
  Hexagram(
    id: 7,
    name: '지수사',
    hanja: '地水師',
    binary: '010000',
    summary: '전쟁과 군대',
  ),
  Hexagram(
    id: 8,
    name: '수지비',
    hanja: '水地比',
    binary: '000010',
    summary: '친화와 협력',
  ),
  Hexagram(
    id: 9,
    name: '풍천소축',
    hanja: '風天小畜',
    binary: '111011',
    summary: '작은 것을 쌓음',
  ),
  Hexagram(
    id: 10,
    name: '천택리',
    hanja: '天澤履',
    binary: '110111',
    summary: '예절과 실천',
  ),
  Hexagram(
    id: 11,
    name: '지천태',
    hanja: '地天泰',
    binary: '111000',
    summary: '평화와 소통',
  ),
  Hexagram(
    id: 12,
    name: '천지비',
    hanja: '天地否',
    binary: '000111',
    summary: '비색함과 단절',
  ),
  Hexagram(
    id: 13,
    name: '천화동인',
    hanja: '天火同人',
    binary: '101111',
    summary: '화합과 협업',
  ),
  Hexagram(
    id: 14,
    name: '화천대유',
    hanja: '火天大有',
    binary: '111101',
    summary: '크게 소유함',
  ),
  Hexagram(
    id: 15,
    name: '지산겸',
    hanja: '地山謙',
    binary: '001000',
    summary: '겸손의 미덕',
  ),
  Hexagram(
    id: 16,
    name: '뇌지예',
    hanja: '雷地豫',
    binary: '000100',
    summary: '기쁨과 대비',
  ),
  Hexagram(
    id: 17,
    name: '택뢰수',
    hanja: '澤雷隨',
    binary: '100110',
    summary: '흐름을 따름',
  ),
  Hexagram(
    id: 18,
    name: '산풍고',
    hanja: '山風蠱',
    binary: '011001',
    summary: '부패의 혁신',
  ),
  Hexagram(
    id: 19,
    name: '지택림',
    hanja: '地澤臨',
    binary: '110000',
    summary: '직면과 성장',
  ),
  Hexagram(
    id: 20,
    name: '풍지관',
    hanja: '風地觀',
    binary: '000011',
    summary: '관찰과 통찰',
  ),
  Hexagram(
    id: 21,
    name: '화뢰서합',
    hanja: '火雷噬嗑',
    binary: '100101',
    summary: '결단과 법령',
  ),
  Hexagram(
    id: 22,
    name: '산화비',
    hanja: '山火賁',
    binary: '101001',
    summary: '꾸밈과 장식',
  ),
  Hexagram(
    id: 23,
    name: '산지박',
    hanja: '山地剝',
    binary: '000001',
    summary: '벗겨지고 깎임',
  ),
  Hexagram(
    id: 24,
    name: '지뢰복',
    hanja: '地雷復',
    binary: '100000',
    summary: '회복과 복귀',
  ),
  Hexagram(
    id: 25,
    name: '천뢰무망',
    hanja: '天雷無妄',
    binary: '100111',
    summary: '순수와 정당함',
  ),
  Hexagram(
    id: 26,
    name: '산천대축',
    hanja: '山天大畜',
    binary: '111001',
    summary: '큰 축적',
  ),
  Hexagram(
    id: 27,
    name: '산뢰이',
    hanja: '山雷頤',
    binary: '100001',
    summary: '기름과 양식',
  ),
  Hexagram(
    id: 28,
    name: '택풍대과',
    hanja: '澤風大過',
    binary: '011110',
    summary: '지나친 부담',
  ),
  Hexagram(
    id: 29,
    name: '중수감',
    hanja: '重水坎',
    binary: '010010',
    summary: '험난함의 극복',
  ),
  Hexagram(
    id: 30,
    name: '중화리',
    hanja: '重火離',
    binary: '101101',
    summary: '분별과 지혜',
  ),
  Hexagram(
    id: 31,
    name: '택산함',
    hanja: '澤山咸',
    binary: '001110',
    summary: '느낌과 교감',
  ),
  Hexagram(
    id: 32,
    name: '뇌풍항',
    hanja: '雷風恒',
    binary: '011100',
    summary: '항구와 지속',
  ),
  Hexagram(
    id: 33,
    name: '천산둔',
    hanja: '天山遁',
    binary: '001111',
    summary: '은둔과 물러남',
  ),
  Hexagram(
    id: 34,
    name: '뇌천대장',
    hanja: '雷天大壯',
    binary: '111100',
    summary: '큰 세력',
  ),
  Hexagram(
    id: 35,
    name: '화지진',
    hanja: '火地晉',
    binary: '000101',
    summary: '전진과 번창',
  ),
  Hexagram(
    id: 36,
    name: '지화명이',
    hanja: '地火明夷',
    binary: '101000',
    summary: '빛의 가려짐',
  ),
  Hexagram(
    id: 37,
    name: '풍화가인',
    hanja: '風火家人',
    binary: '101011',
    summary: '가정과 질서',
  ),
  Hexagram(
    id: 38,
    name: '화택규',
    hanja: '火澤睽',
    binary: '110101',
    summary: '어긋남과 반목',
  ),
  Hexagram(
    id: 39,
    name: '수산건',
    hanja: '水山蹇',
    binary: '001010',
    summary: '절음발이 어려움',
  ),
  Hexagram(
    id: 40,
    name: '뇌수해',
    hanja: '雷水解',
    binary: '010100',
    summary: '풀림과 해결',
  ),
  Hexagram(
    id: 41,
    name: '산택손',
    hanja: '山澤損',
    binary: '110001',
    summary: '덜어냄과 이익',
  ),
  Hexagram(
    id: 42,
    name: '풍뢰익',
    hanja: '風雷益',
    binary: '100011',
    summary: '더함과 유익',
  ),
  Hexagram(
    id: 43,
    name: '택천쾌',
    hanja: '澤天夬',
    binary: '111110',
    summary: '터짐과 결단',
  ),
  Hexagram(
    id: 44,
    name: '천풍구',
    hanja: '天風姤',
    binary: '011111',
    summary: '우연한 만남',
  ),
  Hexagram(
    id: 45,
    name: '택지췌',
    hanja: '澤地萃',
    binary: '000011',
    summary: '모임과 집합',
  ),
  Hexagram(
    id: 46,
    name: '지풍승',
    hanja: '地風升',
    binary: '011000',
    summary: '상승과 성장',
  ),
  Hexagram(
    id: 47,
    name: '택수곤',
    hanja: '澤水困',
    binary: '010110',
    summary: '곤경과 막힘',
  ),
  Hexagram(
    id: 48,
    name: '수풍정',
    hanja: '水風井',
    binary: '011010',
    summary: '우물과 생명력',
  ),
  Hexagram(
    id: 49,
    name: '택화혁',
    hanja: '澤火革',
    binary: '101110',
    summary: '변혁과 개혁',
  ),
  Hexagram(
    id: 50,
    name: '화풍정',
    hanja: '火風鼎',
    binary: '011101',
    summary: '솥과 새로운 시작',
  ),
  Hexagram(
    id: 51,
    name: '중뇌진',
    hanja: '重雷震',
    binary: '100100',
    summary: '우레와 행동',
  ),
  Hexagram(
    id: 52,
    name: '중산간',
    hanja: '重山艮',
    binary: '001001',
    summary: '그침과 고요함',
  ),
  Hexagram(
    id: 53,
    name: '풍산점',
    hanja: '風山漸',
    binary: '001011',
    summary: '점진적 나아감',
  ),
  Hexagram(
    id: 54,
    name: '뇌택귀매',
    hanja: '雷澤歸妹',
    binary: '110100',
    summary: '누이의 출가',
  ),
  Hexagram(
    id: 55,
    name: '뇌화풍',
    hanja: '雷火豊',
    binary: '101100',
    summary: '풍성함과 성대함',
  ),
  Hexagram(
    id: 56,
    name: '화산려',
    hanja: '火山旅',
    binary: '001101',
    summary: '나그네의 길',
  ),
  Hexagram(
    id: 57,
    name: '중풍손',
    hanja: '重風巽',
    binary: '011011',
    summary: '순종과 공손함',
  ),
  Hexagram(
    id: 58,
    name: '중택태',
    hanja: '重澤兌',
    binary: '110110',
    summary: '기쁨과 연못',
  ),
  Hexagram(
    id: 59,
    name: '풍수환',
    hanja: '風水渙',
    binary: '010011',
    summary: '흩어짐과 풀림',
  ),
  Hexagram(
    id: 60,
    name: '수택절',
    hanja: '水澤節',
    binary: '110010',
    summary: '절제와 규율',
  ),
  Hexagram(
    id: 61,
    name: '풍택중부',
    hanja: '風澤中孚',
    binary: '110011',
    summary: '정성과 믿음',
  ),
  Hexagram(
    id: 62,
    name: '뇌산소과',
    hanja: '雷山小過',
    binary: '001100',
    summary: '작은 허물',
  ),
  Hexagram(
    id: 63,
    name: '수화기제',
    hanja: '水火旣濟',
    binary: '101010',
    summary: '이미 이루어짐',
  ),
  Hexagram(
    id: 64,
    name: '화수미제',
    hanja: '火水未濟',
    binary: '010101',
    summary: '아직 끝나지 않음',
  ),
];
